[package]
name = "derivator-utils"
version = "0.1.0"
edition = "2021"
authors = [
  "Bjorn Ove Hay Andersen <bjrnove@gmail.com>",
]
license = "MIT OR Apache-2.0"

[dependencies]
quote = "1.0.23"
syn = "1.0.109"
